### ISSUE TITLE
Multiple Issues in the Connect-M365SAT.ps1 module 

### ISSUE THREAD

**Issue by StefaSpam** [CompliantSec/M365SAT#76]
Hello,
I keep getting the following error:

04/10/2025 16:46:30: Initiating Connections...
WARNING: 16:46:30 - You may need to login again after updating "EnableLoginByWam".
WARNING: The names of some imported commands from the module 'Microsoft.Online.SharePoint.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The names of some imported commands from the module 'Microsoft.Online.SharePoint.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The names of some imported commands from the module 'Microsoft.Online.SharePoint.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: Module Microsoft.Online.SharePoint.PowerShell is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.

Exception: C:\M365SAT\core\Connect-M365SAT.ps1:142
Line |
 142 |          throw "Failed to retrieve a valid organization name from any  …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Failed to retrieve a valid organization name from any module.

The configured parameters are:
    OutPath          = "C:\M365SAT"
    Username         = "xxxxx@yyy.zzz"
    EnvironmentType  = "M365"
    Modules          = "Office365"
    LicenseMode      = "All"        
    LicenseLevel     = "All"          
    ReportType       = "HTML" 

Thank you
Stefa

**Comment by Karmakstylez** [comment]
Hi @StefaSpam ,

To get to help you better I must have some more information. Please include the following:
- PowerShell version
- Are you using the M365SATTester.ps1 here?
- Please give me the list of all installed PowerShell cmdlets and their version regarding the list you need to install.
Please kindly let me know so I can proceed to check where the issue might lay.

Kind regards,

~LvdW

**Comment by StefaSpam** [comment]
Hi
thank you for the quick reply. These are the info requied:
- Powershell Version: PowerShell 7.5.0 on Windows11 24H2
- Are you using the M365SATTester.ps1 here? Yes
- List installed modules:
M365SAT - The Official Microsoft 365 Security Audit Tool - Version 3.1 beta - Leonardo van de Weteringh - 24th of March 2025
I wish you happy auditting! :)
04/10/2025 19:27:56: Checking Existence SkipChecks Parameter...
04/10/2025 19:27:56 Performing M365SAT Version check...
WARNING: [?] Checking Installed Modules...
[+] MicrosoftTeams version 6.9.0 is installed.
[+] Az version 13.4.0 is installed.
[+] ExchangeOnlineManagement version 3.7.2 is installed.
[+] Microsoft.Graph version 2.26.1 is installed.
[+] Microsoft.Graph.Beta version 2.26.1 is installed.
[+] PoShLog version 2.1.1 is installed.
[+] PnP.PowerShell version 2.12.0 is installed.
All required modules are installed successfully!
Module 'MicrosoftTeams' is up-to-date (Installed: 6.9.0, Online: 6.9.0).
Module 'Az' is up-to-date (Installed: 13.4.0, Online: 13.4.0).
Module 'ExchangeOnlineManagement' is up-to-date (Installed: 3.7.2, Online: 3.7.2).
Module 'Microsoft.Graph' is up-to-date (Installed: 2.26.1, Online: 2.26.1).
Module 'Microsoft.Graph.Beta' is up-to-date (Installed: 2.26.1, Online: 2.26.1).
Module 'PnP.PowerShell' is up-to-date (Installed: 2.12.0, Online: 2.12.0).
Checking module: MicrosoftTeams
MicrosoftTeams has 6.9.0 with 03/13/2025 10:57:33
Only one version of 'MicrosoftTeams' is installed (6.9.0). Skipping removal.
Checking module: Az
Az has 13.4.0 with 04/01/2025 06:28:49
Only one version of 'Az' is installed (13.4.0). Skipping removal.
Checking module: ExchangeOnlineManagement
ExchangeOnlineManagement has 3.7.2 with 03/21/2025 12:33:57
Uninstalling older version 3.7.0 of 'ExchangeOnlineManagement'...
WARNING: Failed to uninstall version 3.7.0 of 'ExchangeOnlineManagement'.
WARNING: Please manually uninstall using: Uninstall-Module -Name ExchangeOnlineManagement -RequiredVersion 3.7.0 -Force
Checking module: Microsoft.Online.Sharepoint.PowerShell
Microsoft.Online.Sharepoint.PowerShell has 16.0.25912.12000 with 03/31/2025 12:46:39
WARNING: The latest installed version of 'Microsoft.Online.Sharepoint.PowerShell' (16.0.24510.12000) is outdated compared to the online version (16.0.25912.12000).
Only one version of 'Microsoft.Online.Sharepoint.PowerShell' is installed (16.0.24510.12000). Skipping removal.
Checking module: Microsoft.Graph
Microsoft.Graph has 2.26.1 with 02/26/2025 01:09:12
Only one version of 'Microsoft.Graph' is installed (2.26.1). Skipping removal.
Checking module: Microsoft.Graph.Beta
Microsoft.Graph.Beta has 2.26.1 with 02/26/2025 01:09:16
Only one version of 'Microsoft.Graph.Beta' is installed (2.26.1). Skipping removal.
Checking module: PoShLog
PoShLog has 2.1.1 with 07/13/2020 12:44:35
Only one version of 'PoShLog' is installed (2.1.1). Skipping removal.
Checking module: PnP.PowerShell
PnP.PowerShell has 2.12.0 with 09/09/2024 11:27:33
Only one version of 'PnP.PowerShell' is installed (2.12.0). Skipping removal.
04/10/2025 19:28:50: Initiating Connections...
WARNING: 19:28:50 - You may need to login again after updating "EnableLoginByWam".
WARNING: The names of some imported commands from the module 'Microsoft.Online.SharePoint.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The names of some imported commands from the module 'Microsoft.Online.SharePoint.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The names of some imported commands from the module 'Microsoft.Online.SharePoint.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: Module Microsoft.Online.SharePoint.PowerShell is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.
Exception: C:\M365SAT\core\Connect-M365SAT.ps1:142
Line |
 142 |          throw "Failed to retrieve a valid organization name from any  …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Failed to retrieve a valid organization name from any module.

If you need more info/details, let me know

Thank you
Stefa

**Comment by Karmakstylez** [comment]
Interesting...

I have successfully reproduced the issue. It seems to be an issue in the Connect-M365SAT.ps1. I will release a quick fix for you. This will be implemented tomorrow. I will notify here once it has been implemented so you can test it again. 

~LvdW

**Comment by Karmakstylez** [comment]
Update:

I have pushed the fix through to the `production` branch after some testing. Could you retest your use-case and verify for me if everything works like normal?

Thanks in advance.

~LvdW

**Comment by StefaSpam** [comment]
Hi
the org name issue seems resolved, and it asked me to authenticate 3 times.
But the second time it redirects to the browser to url: http://localhost:7099/?code=1.AVwAIUnJCbU7w0iNyvAnLggLlew............. and fails (ERR_CONNECTION_REFUSED). 

And then it files with the following errors:

Connecting to Microsoft Azure PowerShell... (Attempt 1 of 3)
Please select the account you want to login with.

Retrieving subscriptions for the selection...
WARNING: To override which subscription Connect-AzAccount selects by default, use `Update-AzConfig -DefaultSubscriptionForLogin 00000000-0000-0000-0000-000000000000`. Go to https://go.microsoft.com/fwlink/?linkid=2200610 for more information.
Connected to Microsoft Azure PowerShell!
Connecting to Microsoft Graph... (Attempt 1 of 3)
Connected to Microsoft Graph!
04/11/2025 08:07:28: Getting Inspectors...
Get-ChildItem: C:\M365SAT\core\Get-M365SATChecks.ps1:94
Line |
  94 |  … nspectors = Get-ChildItem $Directory\$M365Folder\$Module\$E3Folder\$L …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\M365SAT\inspectors\M365\Office365\E3\L1' because it does not exist.
Get-ChildItem: C:\M365SAT\core\Get-M365SATChecks.ps1:103
Line |
 103 |  … nspectors = Get-ChildItem $Directory\$M365Folder\$Module\$E3Folder\$L …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\M365SAT\inspectors\M365\Office365\E3\L2' because it does not exist.
Get-ChildItem: C:\M365SAT\core\Get-M365SATChecks.ps1:117
Line |
 117 |  … nspectors = Get-ChildItem $Directory\$M365Folder\$Module\$E5Folder\$L …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\M365SAT\inspectors\M365\Office365\E5\L1' because it does not exist.
Get-ChildItem: C:\M365SAT\core\Get-M365SATChecks.ps1:126
Line |
 126 |  … nspectors = Get-ChildItem $Directory\$M365Folder\$Module\$E5Folder\$L …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\M365SAT\inspectors\M365\Office365\E5\L2' because it does not exist.
04/11/2025 08:07:28: Executing Inspectors in SingleThread Mode...
04/11/2025 08:07:28: Generating Report...
Get-M365SATReport: C:\M365SAT\M365SATTester.ps1:41
Line |
  41 |          Get-M365SATReport @PSBoundParameters
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Attempted to divide by zero.


Thank you
Stefa

**Comment by Karmakstylez** [comment]
Hello @StefaSpam ,

Thank you for reporting that the issue has been resolved.

The other issue is regarding your inspector folder. You are trying to execute the full M365 suite with O365 only to audit which is now currently a paid option. The announcement in the README.md says something about that. You can find information about M365SAT itself here: https://compliantsec.nl/m365sat/ 

I will make a 'free suite' available with some limited scans. If you are willing to scan the whole suite of O365 you can contact via CompliantSec to discuss about the needs. Once that will be available, I will report back into here. This could take a little bit of time, I thank you for your patience.

~LvdW

**Comment by StefaSpam** [comment]
Now I kept the default settings, I was simply trying to limit the audit.

Now the script asked for authentication 4th times, and the third was to http://localhost:9376/?code=1.AVwAIUnJ.....

The output was:
Connecting to Microsoft Graph... (Attempt 1 of 3)
Connected to Microsoft Graph!
Connecting to Microsoft Teams... (Attempt 1 of 3)
Connected to Microsoft Teams!
Connecting to Microsoft Azure PowerShell... (Attempt 1 of 3)
Please select the account you want to login with.

Retrieving subscriptions for the selection...
WARNING: To override which subscription Connect-AzAccount selects by default, use `Update-AzConfig -DefaultSubscriptionForLogin 00000000-0000-0000-0000-000000000000`. Go to https://go.microsoft.com/fwlink/?linkid=2200610 for more information.
Connected to Microsoft Azure PowerShell!
Connecting to Microsoft Exchange... (Attempt 1 of 3)
WARNING: Attempt 1 failed: Method not found: 'Microsoft.Identity.Client.PublicClientApplicationBuilder Microsoft.Identity.Client.Broker.BrokerExtension.WithBroker(Microsoft.Identity.Client.PublicClientApplicationBuilder, Microsoft.Identity.Client.BrokerOptions)'.
Connecting to Microsoft Exchange... (Attempt 2 of 3)
WARNING: Attempt 2 failed: Method not found: 'Microsoft.Identity.Client.PublicClientApplicationBuilder Microsoft.Identity.Client.Broker.BrokerExtension.WithBroker(Microsoft.Identity.Client.PublicClientApplicationBuilder, Microsoft.Identity.Client.BrokerOptions)'.
Connecting to Microsoft Exchange... (Attempt 3 of 3)
WARNING: Attempt 3 failed: Method not found: 'Microsoft.Identity.Client.PublicClientApplicationBuilder Microsoft.Identity.Client.Broker.BrokerExtension.WithBroker(Microsoft.Identity.Client.PublicClientApplicationBuilder, Microsoft.Identity.Client.BrokerOptions)'.
Write-Error: C:\M365SAT\core\Connect-M365SAT.ps1:105
Line |
 105 |  … hangeAuth = Invoke-MicrosoftExchangeConnection -Username $Username -C …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Maximum number of retry attempts reached. Unable to connect to Microsoft Exchange.
OperationStopped: Method not found: 'Microsoft.Identity.Client.PublicClientApplicationBuilder Microsoft.Identity.Client.Broker.BrokerExtension.WithBroker(Microsoft.Identity.Client.PublicClientApplicationBuilder,
Microsoft.Identity.Client.BrokerOptions)'.

Thank you
S

**Comment by Karmakstylez** [comment]
@StefaSpam ,

Thank you for reporting the other issue. Please do the following:
- Please remove the MicrosoftExchangeOnline module from the PowerShell 7 folder and from the PowerShell 5 folder and install the latest version available which includes the -DisableWAM option. Then it should work on Windows machines.

It seems that you are using the old version of the MicrosoftExchangeOnline connector which does not support the -DisableWAM parameter.

The localhost things are fine. Please keep them active until the scan is complete. If you close hem while running the scan you might run into authentication issues. 

~LvdW

**Comment by StefaSpam** [comment]
I did some tests, but it is still not working.

On my PC, I removed everything, uninstalled PowerShell 7, clean profiles and all folders, and reinstalled it from scratch.
Than I tried with a completely new vanilla OS (Win sandbox), where I installed for the forst time Powershell 7 and all required modules.

Please find attached the 2 outputs.

Thank you
S

[Win11_Sandbox.txt](https://github.com/user-attachments/files/19702807/Win11_Sandbox.txt)

[OLD_Win11.txt](https://github.com/user-attachments/files/19702792/OLD_Win11.txt)

**Comment by Karmakstylez** [comment]
@StefaSpam 

Can you please share the `Connect-MicrosoftExchange.ps1` with me please?

Thanks in advance.

~LvdW

**Comment by StefaSpam** [comment]
[Connect-MicrosoftExchange.ps1.txt](https://github.com/user-attachments/files/19703414/Connect-MicrosoftExchange.ps1.txt)

**Comment by Karmakstylez** [comment]
Okay, this will take longer than expected. I will need to look into the whole schema here to see what is wrong here. When I have more information and on how it should work, I will report it back.

Update: It seems to be a conflict on Windows with the Exchange and the AzAccount cmdlet. I will need to investigate on what the problem really is and see if I can provide a solution.

~LvdW

**Comment by StefaSpam** [comment]
Thank you
In the mean time I contact you via the form on https://compliantsec.nl/m365sat/ with my work email to get some info on the full featured tool.

Let me know when you want me to do some test.

Thank you
S

**Comment by Karmakstylez** [comment]
Hi @StefaSpam ,

I haven't received the email yet, but I have pushed a new fix through Production. If you can test it for me if it now works properly that would be great. I have changed the mechanism as well.

What you should do if you are using PowerShell 7 is the following:
```
Get-InstalledModule -Name Az.Accounts | Uninstall-Module
Install-Module -Name Az.Accounts -RequiredVersion 2.19.0
Install-Module -Name ExchangeOnlineManagement -RequiredVersion 3.6.0
```

If you have installed the modules through PowerShell 5, please do these commands through PowerShell 5.

This will make it work for Windows machines running on Windows 11 supporting WAM as WAM is very buggy and does not work very well and results in errors. ExchangeOnlineManagement 3.6.0 should be used as the 3.7.0 and later has severe issues with AzAccount. I cannot do anything about that yet as that is something which is implemented in the code of the connector. 

I have removed the -DisableWAM parameter for now as that is not supported by 3.6.0 until further notice. I will keep testing.

If you are using Linux or Unix systems you can use all the latest modules as WAM is not an issue there as that is only a Windows mechanism and it will fallback to browser authentication on Linux/Unix systems.

Please let me know if the authentication flow now works properly.

~LvdW

**Comment by StefaSpam** [comment]
I had to disable the modules check\update, because it uninstalled the ExchangeOnlineManagememnt 3.6.0
Checking module: ExchangeOnlineManagement
ExchangeOnlineManagement has 3.7.2 with 03/21/2025 12:33:57
Uninstalling older version 3.6.0 of 'ExchangeOnlineManagement'...
Successfully uninstalled version 3.6.0 of 'ExchangeOnlineManagement'.

Do you want me to uninstall the 3.7.2?
I reinstalled the 3.6.0 but it gave me the following output with some errors. Consider that we effectively have more than 1 subscription in our tenant:

04/11/2025 15:21:33: Initiating Connections...
WARNING: Upcoming breaking changes in the cmdlet 'Update-AzConfig' :
Parameter `DisableErrorRecordsPersistence` will be deprecated, a new parameter `EnableErrorRecordsPersistence` will be added instead. Writing error records to file system will become opt-in instead of opt-out. This change will happen around May 2024
- The change is expected to take effect in Az version : '12.0.0'
- The change is expected to take effect in Az.Accounts version : '2.X'
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.
WARNING: 15:21:33 - You may need to login again after updating "EnableLoginByWam".
WARNING: The names of some imported commands from the module 'Microsoft.Online.SharePoint.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The names of some imported commands from the module 'Microsoft.Online.SharePoint.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The names of some imported commands from the module 'Microsoft.Online.SharePoint.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: Module Microsoft.Online.SharePoint.PowerShell is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.
Connecting to Microsoft Teams... (Attempt 1 of 3)
Connected to Microsoft Teams!
Connecting to Microsoft Azure PowerShell... (Attempt 1 of 3)
WARNING: TenantId 'xxxxxxxx-zzzz-zzzz-zzzz-yyyyyyyyyyyy' contains more than one active subscription. First one will be selected for further use. To select another subscription, use Set-AzContext.
To override which subscription Connect-AzAccount selects by default, use `Update-AzConfig -DefaultSubscriptionForLogin 00000000-0000-0000-0000-000000000000`. Go to https://go.microsoft.com/fwlink/?linkid=2200610 for more information.
Connected to Microsoft Azure PowerShell!
Connecting to Microsoft Graph... (Attempt 1 of 3)
Connected to Microsoft Graph!
Connect-M365SAT: A parameter cannot be found that matches parameter name 'Environment'.

**Comment by Karmakstylez** [comment]
Hi @StefaSpam ,

That is correct. But in the default configuration of the M365SATTester.ps1 the skipcheck is enabled by default. Can you post the full output for me of the authentication schema and the configuration of your `$scriptconfig` please and remove the emailaddress in the config for me so I can check one more time on the Windows operating system if everything works properly now.

Consider using this:
```
$ScriptConfig = @{
    OutPath          = "/home/example/m365sat/out"                  # Change this path based on your OS (e.g., "C:\Out" for Windows)
    Username         = "example@example.org"                        # Replace with your username
    EnvironmentType  = 'M365','AZURE'                               # Specify the environment type (e.g., M365, AZURE, or All)
    Modules          = "All"                                        # Specify the modules to include (e.g., "All" or specific modules (e.g. 'Azure', 'Exchange', 'Office365', 'Sharepoint', 'Teams' ))
    LicenseMode      = "E3"                                         # Specify the license mode (e.g., "E3", "E5" or "All")
    LicenseLevel     = "All"                                        # Specify the license level (e.g. "L1", "L2" or "All")
    ReportType       = "HTML"                                       # Specify the report type (e.g., "CSV", "HTML")
    AllowLogging     = [switch]::Present                            # Enable logging if needed (true/false)
    LocalMode        = [switch]::Present                            # Enable local mode if needed (true/false)
    SkipChecks       = [switch]::Present                            # Skip checks if needed (true/false)
}
```
Keep those switches there as they are essential for making it work properly. LocalMode is required now else you would not get the inspectors and SkipChecks is recommended as it might cause issues if you have it removed there.

~LvdW

**Comment by StefaSpam** [comment]
I' now using the default settings except for output directory and username (see M365SATTester.ps1 attached)
[M365SATTester.ps1.txt](https://github.com/user-attachments/files/19707293/M365SATTester.ps1.txt)

This is the full output:
PS C:\M365SAT> .\M365SATTester.ps1
Your OS: Windows
[+] Your OS is: Windows running PowerShell: 7
[...] Checking if the script is running as Administrator

    /|    //| |     ___       ____     ____    //   ) )  // | |  /__  ___/
   //|   // | |   //   ) )  //       //       ((        //__| |    / /
  // |  //  | |    __ / /  //__     //__        \\     / ___  |   / /
 //  | //   | |       ) ) //   ) )      ) )       ) ) //    | |  / /
//   |//    | | ((___/ / ((___/ / ((___/ / ((___ / / //     | | / /

M365SAT - The Official Microsoft 365 Security Audit Tool - Version 3.1 beta - Leonardo van de Weteringh - 24th of March 2025
I wish you happy auditting! :)
[15:44:55 WRN] Program Started!
04/11/2025 15:44:55: Checking Existence SkipChecks Parameter...
04/11/2025 15:44:55: Initiating Connections...
WARNING: Upcoming breaking changes in the cmdlet 'Update-AzConfig' :
Parameter `DisableErrorRecordsPersistence` will be deprecated, a new parameter `EnableErrorRecordsPersistence` will be added instead. Writing error records to file system will become opt-in instead of opt-out. This change will happen around May 2024
- The change is expected to take effect in Az version : '12.0.0'
- The change is expected to take effect in Az.Accounts version : '2.X'
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.
WARNING: 15:44:55 - You may need to login again after updating "EnableLoginByWam".
WARNING: The names of some imported commands from the module 'Microsoft.Online.SharePoint.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The names of some imported commands from the module 'Microsoft.Online.SharePoint.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The names of some imported commands from the module 'Microsoft.Online.SharePoint.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: Module Microsoft.Online.SharePoint.PowerShell is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.
Connecting to Microsoft Teams... (Attempt 1 of 3)
Connected to Microsoft Teams!
Connecting to Microsoft Azure PowerShell... (Attempt 1 of 3)
WARNING: TenantId 'xxxxxxxx-zzzz-zzzz-zzzz-yyyyyyyyyyyy' contains more than one active subscription. First one will be selected for further use. To select another subscription, use Set-AzContext.
To override which subscription Connect-AzAccount selects by default, use `Update-AzConfig -DefaultSubscriptionForLogin 00000000-0000-0000-0000-000000000000`. Go to https://go.microsoft.com/fwlink/?linkid=2200610 for more information.
Connected to Microsoft Azure PowerShell!
Connecting to Microsoft Graph... (Attempt 1 of 3)
Connected to Microsoft Graph!
Connect-M365SAT: A parameter cannot be found that matches parameter name 'Environment'.
PS C:\M365SAT>

**Comment by Karmakstylez** [comment]
@StefaSpam ,

There was a typo. It has been fixed now. Please check for me :)

~LvdW

**Comment by StefaSpam** [comment]
Better :-)

But now there something wrong with ExchangeOnlineMAnagement 3.7.2.
I have both versions installed, do I need to remove the 3.7.2?
PS C:\M365SAT> Get-InstalledModule -Name ExchangeOnlineManagement -AllVersions

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
3.6.0                ExchangeOnlineManagement            PSGallery            This is a General Availability (GA) release of the Exchange Online PowerShell …
3.7.2                ExchangeOnlineManagement            PSGallery            This is a General Availability (GA) release of the Exchange Online Powershell …

Output:

Connecting to Microsoft Teams... (Attempt 1 of 3)
Connected to Microsoft Teams!
Connecting to Microsoft Azure PowerShell... (Attempt 1 of 3)
WARNING: TenantId 'xxxxxxxx-zzzz-zzzz-zzzz-yyyyyyyyyyyy' contains more than one active subscription. First one will be selected for further use. To select another subscription, use Set-AzContext.
To override which subscription Connect-AzAccount selects by default, use `Update-AzConfig -DefaultSubscriptionForLogin 00000000-0000-0000-0000-000000000000`. Go to https://go.microsoft.com/fwlink/?linkid=2200610 for more information.
Connected to Microsoft Azure PowerShell!
Connecting to Microsoft Graph... (Attempt 1 of 3)
Connected to Microsoft Graph!
Connecting to Microsoft Exchange... (Attempt 1 of 3)
WARNING: Attempt 1 failed: Could not load file or assembly 'C:\Users\LocalAdm\Documents\PowerShell\Modules\ExchangeOnlineManagement\3.7.2\netCore\Microsoft.Identity.Client.dll'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
Connecting to Microsoft Exchange... (Attempt 2 of 3)
WARNING: Attempt 2 failed: Could not load file or assembly 'C:\Users\LocalAdm\Documents\PowerShell\Modules\ExchangeOnlineManagement\3.7.2\netCore\Microsoft.Identity.Client.dll'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
Connecting to Microsoft Exchange... (Attempt 3 of 3)
WARNING: Attempt 3 failed: Could not load file or assembly 'C:\Users\LocalAdm\Documents\PowerShell\Modules\ExchangeOnlineManagement\3.7.2\netCore\Microsoft.Identity.Client.dll'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
Write-Error: C:\M365SAT\core\Connect-M365SAT.ps1:93
Line |
  93 |  … hangeAuth = Invoke-MicrosoftExchangeConnection -Username $Username -C …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Maximum number of retry attempts reached. Unable to connect to Microsoft Exchange.
OperationStopped: Could not load file or assembly 'C:\Users\LocalAdm\Documents\PowerShell\Modules\ExchangeOnlineManagement\3.7.2\netCore\Microsoft.Identity.Client.dll'. The
located assembly's manifest definition does not match the assembly reference. (0x80131040)

**Comment by Karmakstylez** [comment]
@StefaSpam ,

Yes you should not use ExchangeOnlineManagement 3.7.2 on Windows 11 PowerShell 7. It does not work as it's mechanism conflicts with the Az.Account. This is not the case on PowerShell 5 or PowerShell 7 on Linux due to a different mechanism. 

I have posted the correct instructions in the new README.md on the github page. You should use the following:
- Az.Accounts 2.19.0
- ExchangeOnlineManagement 3.6.0

You can achieve this by doing this:
```
Get-InstalledModule -Name Az.Accounts | Uninstall-Module
Install-Module -Name Az.Accounts -RequiredVersion 2.19.0
Install-Module -Name ExchangeOnlineManagement -RequiredVersion 3.6.0
```

You can remove the new ExchangeOnlineManagement version by navigating to the modules folder and deleting the ExchangeOnlineManagement folder and install ExchangeOnlineManagement v3.6.0 again.

Let me know if you have any questions.

~LvdW

**Comment by StefaSpam** [comment]
Much better now, but it seems there is still a problem with the inspector

Connecting to Microsoft Exchange... (Attempt 1 of 3)
Connected to Microsoft Exchange!
Connecting to Microsoft Security & Compliance... (Attempt 1 of 3)
Connected to Microsoft Security & Compliance!
Connecting to Microsoft PnP PowerShell... (Attempt 1 of 3)
Creating EntraIDAppRegistration for PnP.PowerShell...
WARNING:
 No permissions specified, using default permissions


Checking if application 'PnP Rocks' does not exist yet...Success. Application 'PnP Rocks' can be registered.
App PnP Rocks with id e74f3b58-e8d0-4d75-a3cd-ca700febb312 created.
WARNING:
  
 A newer version of PnP PowerShell is available: 2.99.185-nightly.
  
 Use 'Update-Module -Name PnP.PowerShell' to update.
 Use 'Get-PnPChangeLog -Release 2.99.185-nightly' to list changes.
  
 You can turn this check off by setting the 'PNPPOWERSHELL_UPDATECHECK' environment variable to 'Off'.
  


Connected to Microsoft PnP PowerShell!
04/11/2025 17:10:04: Getting Inspectors...
Get-ChildItem: C:\M365SAT\core\Get-M365SATChecks.ps1:94
Line |
  94 |  … nspectors = Get-ChildItem $Directory\$M365Folder\$Module\$E3Folder\$L …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\M365SAT\inspectors\M365\Azure\E3\L1' because it does not exist.
Get-ChildItem: C:\M365SAT\core\Get-M365SATChecks.ps1:103
Line |
 103 |  … nspectors = Get-ChildItem $Directory\$M365Folder\$Module\$E3Folder\$L …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\M365SAT\inspectors\M365\Azure\E3\L2' because it does not exist.
Get-ChildItem: C:\M365SAT\core\Get-M365SATChecks.ps1:94
Line |
  94 |  … nspectors = Get-ChildItem $Directory\$M365Folder\$Module\$E3Folder\$L …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\M365SAT\inspectors\M365\Exchange\E3\L1' because it does not exist.
Get-ChildItem: C:\M365SAT\core\Get-M365SATChecks.ps1:103
Line |
 103 |  … nspectors = Get-ChildItem $Directory\$M365Folder\$Module\$E3Folder\$L …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\M365SAT\inspectors\M365\Exchange\E3\L2' because it does not exist.
Get-ChildItem: C:\M365SAT\core\Get-M365SATChecks.ps1:94
Line |
  94 |  … nspectors = Get-ChildItem $Directory\$M365Folder\$Module\$E3Folder\$L …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\M365SAT\inspectors\M365\Office365\E3\L1' because it does not exist.
Get-ChildItem: C:\M365SAT\core\Get-M365SATChecks.ps1:103
Line |
 103 |  … nspectors = Get-ChildItem $Directory\$M365Folder\$Module\$E3Folder\$L …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\M365SAT\inspectors\M365\Office365\E3\L2' because it does not exist.
Get-ChildItem: C:\M365SAT\core\Get-M365SATChecks.ps1:94
Line |
  94 |  … nspectors = Get-ChildItem $Directory\$M365Folder\$Module\$E3Folder\$L …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\M365SAT\inspectors\M365\Sharepoint\E3\L1' because it does not exist.
Get-ChildItem: C:\M365SAT\core\Get-M365SATChecks.ps1:103
Line |
 103 |  … nspectors = Get-ChildItem $Directory\$M365Folder\$Module\$E3Folder\$L …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\M365SAT\inspectors\M365\Sharepoint\E3\L2' because it does not exist.
Get-ChildItem: C:\M365SAT\core\Get-M365SATChecks.ps1:94
Line |
  94 |  … nspectors = Get-ChildItem $Directory\$M365Folder\$Module\$E3Folder\$L …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\M365SAT\inspectors\M365\Teams\E3\L1' because it does not exist.
Get-ChildItem: C:\M365SAT\core\Get-M365SATChecks.ps1:103
Line |
 103 |  … nspectors = Get-ChildItem $Directory\$M365Folder\$Module\$E3Folder\$L …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\M365SAT\inspectors\M365\Teams\E3\L2' because it does not exist.
Get-ChildItem: C:\M365SAT\core\Get-M365SATChecks.ps1:146
Line |
 146 |  … $L1Inspectors = Get-ChildItem $Directory\$AZUREFolder\$L1Folder\*.ps1
     |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\M365SAT\inspectors\AZURE\L1' because it does not exist.
Get-ChildItem: C:\M365SAT\core\Get-M365SATChecks.ps1:155
Line |
 155 |  … $L2Inspectors = Get-ChildItem $Directory\$AZUREFolder\$L2Folder\*.ps1
     |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\M365SAT\inspectors\AZURE\L2' because it does not exist.
04/11/2025 17:10:05: Executing Inspectors in SingleThread Mode...
04/11/2025 17:10:05: Generating Report...
Get-M365SATReport: C:\M365SAT\M365SATTester.ps1:40
Line |
  40 |          Get-M365SATReport @PSBoundParameters
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Attempted to divide by zero.
PS C:\M365SAT>

**Comment by Karmakstylez** [comment]
@StefaSpam ,

Yes that is correct behavior, because you do not have any inspectors nor a M365 or AZURE directory within the Inspectors folder. Please read #77 for more information. I am working on the list of 'free limited inspectors' once I have made the list I will include it in the inspectors folder it can be run. What you can do is create your own inspectors and change the `EnvironmentType` to `CUSTOM` and put your own inspectors there. You can find a template on how to make them in the README.md as well.

The inspectors should be placed in CUSTOM > E3 or E5 > L1 or L2
E3/E5 is the license and L1/L2 determines the level of depth so if your custom check is a small check which does not tamper advanced settings you could designate it as L1.

Once I have implemented the 'free inspectors' for testing then you can use the EnvironmentType M365 or AZURE.

~LvdW

**Comment by StefaSpam** [comment]
In the meantime can I test with a different EnvironmentType?

What about the paid version? I will send you a DM in linkedin to discuss about it

**Comment by Karmakstylez** [comment]
@StefaSpam ,

Let me summarize it for you:
- Yes, please use the CUSTOM `EnvironmentType` and create your own inspectors with the template in README.md
- Until the 'Free Limited Inspectors' are released you cannot use the M365 or AZURE `EnvironmentType`
- I think I have sent you an email back through the form, please check your mailbox if you have received it. 

~LvdW

**Comment by StefaSpam** [comment]
Yes, it was classified as spam :-(

I will try with CUSTOM EnvironmentType: I hope I will be able to create a simple inspector

Thank you

**Comment by Karmakstylez** [comment]
@StefaSpam ,

If you need help with it feel free to contact me. Also, if you are wishing to build your own benchmark to implement, I could help you with that as well. We then could look at how you want to setup the tenants and extract possible settings so I can create inspectors for you. That is also a service I could deliver. :)

You can contact me also on LinkedIn or at the email I have sent to you.

Have a nice weekend.

~LvdW

**Comment by Karmakstylez** [comment]
Please let me know if this issue has been resolved.

~Kz
